# Site settings
title: José Antonio Campillo
email: campi1112@hotmail.com
url: #https://example.github.io
description: "Inquietudes, avances, proyectos"
keywords: "Javascript, Java, Python, Docker, Networking"
skills: #"Web Developer - Android Developer - Docker - Networking"
meta_author: José Antonio Campillo

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: joseantonio

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c 
  primary-rgb: "24,288,156"
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: JACE SPAIN
  # location: SPAIN
  social: #Around the Web
  credits: #Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/c4mpi
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: #http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: #http://bitbucket.org/jekyll
  - title: github
    url: https://joseantoniocampillo.github.io/

# Postal address (add as many lines as necessary)
address:
  - line: Murcia
  - line: SPAIN

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
