version: '2'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --incremental --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - p:/javascript/joseantoniocampillo.github.io:/srv/jekyll